package cn.bjtc.api;

public enum BaseDictType {

	DICT_PRIVTYPE,DICT_PRIVCAT,DICT_PRIVST,DICT_EDU,DICT_DEPARTID,
	DICT_GENDER,DICT_STAFFST,DICT_DEPARTST,DICT_CERRTTYPE,DICT_CSTMTYPE,
	DICT_IDDEFAULT,DICT_OBJTYPE,DICT_CHANTYPE,DICT_CHANST,DICT_SUPPLV,
	DICT_ISOPENSHOP,DICT_ROLEST,DICT_MENUST,DICT_ELEMST,DICT_ALARMST,
	DICT_REGIONST,DICT_BRANDST,DICT_CASTST,DICT_FROMSYS,DICT_SPECTYPE,
	DICT_SPECST,DICT_PARAMTYPE,DICT_PARAMST,DICT_ORDER,DICT_FACTUNIT,
	DICT_ORDERTYPE,DICT_PAYTYPE,DICT_ACTTYPE,DICT_ACTCAT,DICT_ACTST,
	DICT_PRIDUCTST,DICT_ISDISPLAY,DICT_CHECKST,DICT_APIST,DICT_ALARMTYPE, DICT_DICTST, DICT_CSTMST, DICT_PARENT, DICT_DICTTY,DICT_BIZTYPE,DICT_EVTSTATS;
	
}
